# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: macOS
  pool:
    vmIMage: 'macOS-10.13'
  steps:
  # manually creating the binary path is awkward, but we otherwise
  # end up with permission issues creating the conda env
  # manually cleaning the path now as well because the 
  # cleanEnvironment azure conda directive doesn't seem
  # to have sufficient permissions
  - script: rm -rf /usr/local/miniconda/envs/python36/bin || true
  - script: sudo mkdir -p /usr/local/miniconda/envs/python36/bin
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'python36'
      packageSpecs: 'python=3.6 cython pathlib pytz pytest pytest-xdist'
      updateConda: True
  - script: source activate python36; conda list; which python; python runtests.py
    displayName: 'Build and Run Tests'
