# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# NOTE: the full test suite isn't passing on Azure macos yet

jobs:
- job: macOS
  pool:
    vmIMage: 'macOS-10.13'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: python -m pip install cython pathlib pytz pytest pytest-xdist
    displayName: 'Install dependencies'
  - script: python runtests.py
    displayName: 'Build and Run Tests'
